export const propertiesMappings: Record<string, string> = {
  wojewodztwo: "Województwo",
  miasto: "Miasto",
  dzielnica: "Dzielnica",
  okolica: "Okolica",
  ulica: "Ulica",
  location_nr: "Lokalizacja numer",
  zip_code: "Kod pocztowy",
  dataaktualizacji: "Data aktualizacji",
  rynek_pierwotny: "Rynek pierwotny",
  przetarg: "Przetarg",
  termin_przetargu: "Termin przetargu",
  vadium: "Vadium",
  publikujulice: "Publikuj ulice",
  powierzchnia: "Powierzchnia",
  available_area: "Available area",
  liczbapokoi: "Liczba pokoi",
  liczbatelefonow: "Liczba telefonow",
  pietro: "Piętro",
  liczbapieter: "Liczba pięter",
  liczba_poziomow: "Liczba poziomów",
  winda: "Winda",
  rokbudowy: "Rok budowy",
  materialbudowy: "Materiał budowy",
  typkuchni: "Typ kuchni",
  miejscaparkingowe: "Miejsca parkingowe",
  opis: "Opis",
  biuro: "Biuro",
  meble: "Meble",
  agent_nazwisko: "Agent nazwisko",
  agent_email: "Agent email",
  agent_tel_biuro: "Agent telefon biuro",
  agent_tel_kom: "Agent telefon komórkowy",
  numer_licencji_posrednika: "Numer licencji pośrednika",
  zwalnianeod: "Zwalniane od",
  wysokoscpomieszczen: "Wysokość pomieszczeń",
  napoddaszu: "Na poddaszu",
  dwupoziomowe: "Dwupoziomowe",
  balkon: "Balkon",
  taras: "Taras",
  piwnica: "Piwnica",
  piecykgazowy: "Piecyk gazowy",
  pralka: "Pralka",
  lodowka: "Lodówka",
  kuchniawyposazona: "Kuchnia wyposażona",
  telewizor: "Telewizor",
  internet: "Internet",
  osiedle_zamkniete: "Osiedle zamknięte",
  wylacznosc: "Wylaczność",
  bezprowizji: "Bez prowizji",
  forma_wlasnosci: "Forma własności",
  zamiana: "Zamiana",
  opis_zamiana: "Opis zamiana",
  lazienka_wc: "Łazienka wc",
  klimatyzacja: "Klimatyzacja",
  czy_stan_deweloperski: "Czy stan deweloperski",
  powierzchnia_balkonu: "Powierzchnia balkonu",
  powierzchnia_lazienki: "Powierzchnia łazienki",
  liczbalazienek: "Liczba łazienek",
  liczba_sypialni: "Liczba sypialni",
  liczba_wind: "Liczba wind",
  ma_kominek: "Ma kominek",
  ma_gaz: "Ma gaz",
  ma_domofon: "Ma domofon",
  ma_telefon: "Ma telefon",
  ma_ogrzewanie: "Ma ogrzewanie",
  gaz: "Gaz",
  rodzajlacz: "Rodzaj łaczenia internetu",
  stannieruchomosci: "Stan nieruchomosci",
  stanbudynku: "Stan budynku",
  ogrzewanie: "Ogrzewanie",
  kaucja: "Kaucja",
  typ_podlogi: "Typ podlogi",
  oswietlenie: "Oświetlenie",
  stolarka_okienna: "Stolarka okienna",
  kierunekokien: "Kierunek okien",
  dodatkowe_koszty: "Dodatkowe koszty",
  czas_wynajmu: "Czas wynajmu",
  ma_rampe: "Ma rampę",
  taras_powierzchnia: "Taras powierzchnia",
  loggia_powierzchnia: "Loggia powierzchnia",
  ogrodek_powierzchnia: "Powierzchnia ogródka",
  ma_pom_socjalne: "Pomieszenie socjalne",
  liczba_miejsc_parkingowych: "Liczba miejsc parkingowych",
  has_suites: "Apartamenty",
  czy_cena_do_negocjacji: "Czy cena do negocjacji",
  opis_ang: "Opis (english)",
  typbudynkumieszk: "Typ budynku mieszkalnego",
  przyjazne_zwierzetom: "Przyjazne zwierzętom",
  advertisement_text: "Advertisement_text",
  wirtualnawizyta: "Wirtualna wizyta",
  has_garden: "Ogród",
  has_loggia: "Loggia",
  powierzchniadzialki: "Powierzchnia działki",
  typzabudowy: "Typ zabudowy",
  typpodlaczeniawody: "Typ podłączenia wody",
  szerokoscdzialki: "Szerokość działki",
  dlugoscdzialki: "Dlugość działki",
  ogrodzenie: "Ogrodzenie",
  drogadojazdowa: "Droga dojazdowa",
  urzadzonyogrod: "Urzadzony ogród",
  prad: "Prąd",
  sila: "Siła",
  kanalizacja: "Kanalizacja",
  cenazametr: "Cena za metr",
  ma_wode: "Ma wodę",
  ma_kanalizacje: "Ma kanalizacje",
  typdachu: "Typ dachu",
  uzbrojenie: "Uzbrojenie",
  typdzialki: "Typ dzialki",
  typdzialkikomercyjne: "Typ dzialki komercyjne",
  typlokalu: "Typ lokalu",
  liczbapomieszczen: "Liczba pomieszczeń",
  zabezpieczenia: "Zabezpieczenia",
  przeznaczenie: "Przeznaczenie",
  ma_witryne: "Ma witrynę",
  typ_biura: "Typ biura",
  property_type: "Rodzaj nieruchomości",
  transaction_type: "Typ transakcji",
  location: "Lokalizacja",
  price: "Cena",
  currency: "Waluta",
};
