export const propertiesMappings: {
  normal: Record<string, string>;
  params: Record<string, string>;
  keywords: Record<string, string>;
} = {
  normal: {
    advertisement_text: "title",
    imoId: "id",
    price: "price",
    currency: "currency",
    location: "location",
    opis: "description",
    agent_nazwisko: "agent_surname",
    agent_email: "agent_email",
    agent_tel_biuro: "office_phone_number",
    agent_tel_kom: "agent_phone_number",
    slug: "slug",
    photos: "photos",
  },
  params: {
    imoId: "id",
    transaction_type: "Typ transakcji",
    rynek_pierwotny: "Rynek pierwotny",
    powierzchnia: "Powierzchnia",
    liczbapokoi: "Liczba pokoi",
    pietro: "Piętro",
    liczbapieter: "Liczba pięter",
    winda: "Winda",
    rokbudowy: "Rok budowy",
    materialbudowy: "Materiał budowy",
    typkuchni: "Typ kuchni",
    miejscaparkingowe: "Miejsca parkingowe",
    biuro: "Może być przeznaczone na biuro",
    meble: "Meble",
    numer_licencji_posrednika: "Numer licencji pośrednika",
    wysokoscpomieszczen: "Wysokość pomieszczeń",
    napoddaszu: "Na poddaszu",
    dwupoziomowe: "Dwupoziomowe",
    balkon: "Balkon",
    taras: "Taras",
    piwnica: "Piwnica",
    piecykgazowy: "Piecyk gazowy",
    pralka: "Pralka",
    lodowka: "Lodówka",
    kuchniawyposazona: "Kuchnia wyposażona",
    telewizor: "Telewizor",
    internet: "Internet",
    osiedle_zamkniete: "Osiedle zamknięte",
    forma_wlasnosci: "Forma własności",
    lazienka_wc: "Łazienka i WC są razem czy osobno",
    klimatyzacja: "Klimatyzacja",
    czy_stan_deweloperski: "Czy stan deweloperski",
    powierzchnia_balkonu: "Powierzchnia balkonu",
    powierzchnia_lazienki: "Powierzchnia łazienki",
    liczbalazienek: "Liczba łazienek",
    liczba_sypialni: "Liczba sypialni",
    liczba_wind: "Liczba wind",
    rodzajlacz: "Rodzaj łaczenia internetu",
    stannieruchomosci: "Stan nieruchomosci",
    stanbudynku: "Stan budynku",
    ogrzewanie: "Ogrzewanie",
    kaucja: "Kaucja",
    typ_podlogi: "Typ podlogi",
    oswietlenie: "Oświetlenie",
    stolarka_okienna: "Stolarka okienna",
    kierunekokien: "Kierunek okien",
    czas_wynajmu: "Czas wynajmu",
    taras_powierzchnia: "Taras powierzchnia",
    has_loggia: "Loggia",
    loggia_powierzchnia: "Loggia powierzchnia",
    ogrodek_powierzchnia: "Powierzchnia ogródka",
    liczba_miejsc_parkingowych: "Liczba miejsc parkingowych",
    typbudynkumieszk: "Typ budynku mieszkalnego",
    wirtualnawizyta: "Wirtualna wizyta",
    powierzchniadzialki: "Powierzchnia działki",
    typzabudowy: "Typ zabudowy",
    typpodlaczeniawody: "Typ podłączenia wody",
    szerokoscdzialki: "Szerokość działki",
    dlugoscdzialki: "Dlugość działki",
    ogrodzenie: "Ogrodzenie",
    drogadojazdowa: "Droga dojazdowa",
    prad: "Prąd",
    sila: "Siła",
    kanalizacja: "Kanalizacja",
    cenazametr: "Cena za metr",
    typdachu: "Typ dachu",
    uzbrojenie: "Uzbrojenie",
    typdzialki: "Typ działki",
    typdzialkikomercyjne: "Typ działki komercyjne",
    typlokalu: "Typ lokalu",
    liczbapomieszczen: "Liczba pomieszczeń",
    zabezpieczenia: "Zabezpieczenia",
    przeznaczenie: "Przeznaczenie",
    typ_biura: "Typ biura",
    property_type: "Rodzaj nieruchomości",
    osiedlezamkniete: "Osiedle zamknięte",
  },
  keywords: {
    ma_gaz: "Gaz",
    ma_domofon: "Domofon",
    ma_telefon: "Telefon",
    ma_ogrzewanie: "Ogrzewanie",
    ma_kominek: "Kominek",
    ma_wode: "Woda",
    ma_kanalizacje: "Kanalizacja",
    gaz: "Gaz",
    has_garden: "Ogród",
  },
};
