export const propertiesMappings: Record<string, string> = {
  imoId: "id",
  advertisement_text: "title",
  rynek_pierwotny: "Rynek pierwotny",
  powierzchnia: "Powierzchnia",
  liczbapokoi: "Liczba pokoi",
  pietro: "Piętro",
  liczbapieter: "Liczba pięter",
  winda: "Winda",
  rokbudowy: "Rok budowy",
  materialbudowy: "Materiał budowy",
  typkuchni: "Typ kuchni",
  miejscaparkingowe: "Miejsca parkingowe",
  opis: "Opis",
  biuro: "Może być przeznaczone na biuro",
  meble: "Meble",
  agent_nazwisko: "Agent nazwisko",
  agent_email: "Adres email agenta",
  agent_tel_biuro: "Telefon biuro",
  agent_tel_kom: "Telefon do agenta",
  numer_licencji_posrednika: "Numer licencji pośrednika",
  wysokoscpomieszczen: "Wysokość pomieszczeń",
  napoddaszu: "Na poddaszu",
  dwupoziomowe: "Dwupoziomowe",
  balkon: "Balkon",
  taras: "Taras",
  piwnica: "Piwnica",
  piecykgazowy: "Piecyk gazowy",
  pralka: "Pralka",
  lodowka: "Lodówka",
  kuchniawyposazona: "Kuchnia wyposażona",
  telewizor: "Telewizor",
  internet: "Internet",
  osiedle_zamkniete: "Osiedle zamknięte",
  forma_wlasnosci: "Forma własności",
  lazienka_wc: "Łazienka i WC są razem czy osobno",
  klimatyzacja: "Klimatyzacja",
  czy_stan_deweloperski: "Czy stan deweloperski",
  powierzchnia_balkonu: "Powierzchnia balkonu",
  powierzchnia_lazienki: "Powierzchnia łazienki",
  liczbalazienek: "Liczba łazienek",
  liczba_sypialni: "Liczba sypialni",
  liczba_wind: "Liczba wind",
  ma_kominek: "Ma kominek",
  ma_gaz: "Ma gaz",
  ma_domofon: "Ma domofon",
  ma_telefon: "Ma telefon",
  ma_ogrzewanie: "Ma ogrzewanie",
  gaz: "Gaz",
  rodzajlacz: "Rodzaj łaczenia internetu",
  stannieruchomosci: "Stan nieruchomosci",
  stanbudynku: "Stan budynku",
  ogrzewanie: "Ogrzewanie",
  kaucja: "Kaucja",
  typ_podlogi: "Typ podlogi",
  oswietlenie: "Oświetlenie",
  stolarka_okienna: "Stolarka okienna",
  kierunekokien: "Kierunek okien",
  czas_wynajmu: "Czas wynajmu",
  taras_powierzchnia: "Taras powierzchnia",
  has_loggia: "Loggia",
  loggia_powierzchnia: "Loggia powierzchnia",
  ogrodek_powierzchnia: "Powierzchnia ogródka",
  liczba_miejsc_parkingowych: "Liczba miejsc parkingowych",
  typbudynkumieszk: "Typ budynku mieszkalnego",
  wirtualnawizyta: "Wirtualna wizyta",
  has_garden: "Ogród",
  powierzchniadzialki: "Powierzchnia działki",
  typzabudowy: "Typ zabudowy",
  typpodlaczeniawody: "Typ podłączenia wody",
  szerokoscdzialki: "Szerokość działki",
  dlugoscdzialki: "Dlugość działki",
  ogrodzenie: "Ogrodzenie",
  drogadojazdowa: "Droga dojazdowa",
  prad: "Prąd",
  sila: "Siła",
  kanalizacja: "Kanalizacja",
  cenazametr: "Cena za metr",
  ma_wode: "Ma wodę",
  ma_kanalizacje: "Ma kanalizację",
  typdachu: "Typ dachu",
  uzbrojenie: "Uzbrojenie",
  typdzialki: "Typ dzialki",
  typdzialkikomercyjne: "Typ dzialki komercyjne",
  typlokalu: "Typ lokalu",
  liczbapomieszczen: "Liczba pomieszczeń",
  zabezpieczenia: "Zabezpieczenia",
  przeznaczenie: "Przeznaczenie",
  typ_biura: "Typ biura",
  property_type: "Rodzaj nieruchomości",
  transaction_type: "Typ transakcji",
  location: "Lokalizacja",
  price: "Cena",
  currency: "Waluta",
  datawprowadzenia: "Data wprowadzenia",
  osiedlezamkniete: "Osiedle zamknięte",
  slug: "slug",
};
